### ISSUE TITLE
"-1 more task" displayed when new task was added in a separate window

### ISSUE THREAD

**Issue by iafan** [evernote/zing#256]
Steps to reproduce:

1. Create 4 priority tasks in some language. Reload the page to make sure the list of tasks is collapsed. You will see "1 more task" label (which is expected).
2. Open a separate browser tab and add one more priority task in the same language (in any translation project or folder)
3. Go back to the first tab and click "1 more task" label.

Expected: the list expands to show 5 unique tasks, the "1 more task" label diappears.

Observed: the list will expand and show 5 tasks, but:
* one of the task lines will appear in the list twice (incorrect)
* the just added task won't show up (incorrect)
* the label will now say "-1 more task" (incorrect)

---

The similar problem happens when a task is _deleted_ in a side tab:

1. Create 4 priority tasks in some language. Reload the page to make sure the list of tasks is collapsed. You will see "1 more task" label (which is expected).
2. Open a separate browser tab and delete one of the priority tasks in the same language
3. Go back to the first tab and click "1 more task" label.

Expected: the list is updated to show only three relevant tasks; "1 more task" label disappears.

Observed: the list is expanded to show 4 tasks; "1 more task" label is still displayed.

---

We can try addressing this by re-fetching the task data on window focus.

**Comment by julen** [comment]
Given that an offset is requested with respect to the list of tasks that were present at page load time (as if it was a _snapshot_), the code assumes the list doesn't change, which is problematic when any changes happen out of the current page because the _snapshot_ becomes stale.

It'll be simpler to fix this by always retrieving the list of tasks starting from the beginning (not at the offset), and limiting it in the amount of items to display. This would be the same as we do for reloading the list in a timely fashion, and the resulting list will always be accurate.
