### ISSUE TITLE
Document building website with `npm run start` command

### ISSUE THREAD

**Issue by NickVolynkin** [evernote/zing#352]
To reproduce:

1. build website with `make docs` from project's root directory 
2. open `website/build/zing/index.html`. 

All links, including those to pages, images and css files are abolute and start with `/zing/...`. This prevents them from loading and the website doesn't look the way it looks when deployed.

Fixing this would really help with working on documentation.

**Comment by julen** [comment]
Thanks for the report @NickVolynkin.

For development changes and working on docs `cd website && npm run start` is prefered and works fine. That fires up a development server and changes are immediately effective in the browser.

Building via `make docs` hasn't been used for local development, but as a means to build the site for deployment and checking docs don't break during CI builds.

The fact that making a build and opening the contents locally doesn't display static files as it does on the web is because of the difference in base URL (note '/zing/' there). Also building creates files with some GitHub pages-specific considerations, like clean URLs, which will never work in local builds.

We could add a `make docs-dev` target if it makes things more discoverable. Please let us know if that would help or if you have other suggestions.

**Comment by NickVolynkin** [comment]
@julen thanks, I just used `npm run start` and it works. I think it's best to just write about this command in readme or some other place in docs.

**Comment by NickVolynkin** [comment]
I can take this task, maybe next week. @julen what do you say?

**Comment by julen** [comment]
Thanks for your willingness to help @NickVolynkin.

We can add a separate README.md in the _website_ directory — let's keep it simple, concise and straight to the point.

Also note how short forms of commands like `npm start` works the same way as `npm run start`. You can [read more about them on npm docs](https://docs.npmjs.com/misc/scripts).

**Comment by julen** [comment]
This was taken care of in https://github.com/evernote/zing/commit/80e8837506d28edf1d972afe5238b7d0aaab5fb9.

**Comment by NickVolynkin** [comment]
@julen thank you!
