### ISSUE TITLE
Make emojis work as placeables

### ISSUE THREAD

**Issue by iafan** [evernote/zing#458]
With the increasing use of emojis in translation, a nice usability improvement would be to make all emojis act like _placeables_ (i.e. clickable entities in source text).

Example: https://translate.evernote.com/ru/android_evernote/translate/strings.xml.po#unit=1254182
(here, in source text, tags `<i>` and `</i>` are highlighted and can be placed into the translation field at current caret position with a single click).

Relevant code: https://github.com/evernote/zing/blob/8157b44d7a46cf4bdc230a22ec83fa24ce56bcdc/pootle/static/js/utils.js#L116-L138

Relevant discussion on matching emojis with regular expressions in JavaScript:
https://stackoverflow.com/questions/22006218/replace-emoji-unicode-symbol-using-regexp-in-javascript

**Comment by benjamimo1** [comment]
Hello! I'm trying to get into this request and noticed that when clicking the placeable that your provided as an example white-font text is added to the text-field. Is this the expected behavior or a bug?
<img width="944" alt="image" src="https://user-images.githubusercontent.com/26126311/78513506-32c97380-777a-11ea-92ac-dcaf44e85117.png">
Should the format of the placeable clicked be kept when inserted?
I'll start trying to replicate a similar behavior for emojis as requested.

**Comment by iafan** [comment]
@benjamimo1 Since the field is grayed out, this means that you are in read-only mode, and placeables should not be inserted at all. So looks like a separate bug, good catch! I filed https://github.com/evernote/zing/issues/460

The white text seems like a styling issue. Not sure why it's white for you; it's supposed to be gray:
![Screen Shot 2020-04-05 at 18 08 11](https://user-images.githubusercontent.com/1728158/78514885-8e8b0100-7768-11ea-8ae1-d180ee9da6e1.png)
Can you experiment in different browsers and see if it's different there?

When you have editing permissions, the text area will have a black text on white background.

**Comment by julen** [comment]
The styling issue for a disabled textarea is a problem in Safari, will fix that now.
